/* Generated By:JJTree: Do not edit this line. ASTArgs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTArgs extends SimpleNode {
  public ASTArgs(int id) {
    super(id);
  }

  public ASTArgs(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=012f3b721ef138fb505fd1b0c1c88f7c (do not edit this line) */
