/* Generated By:JJTree: Do not edit this line. ASTAssignation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTAssignation extends SimpleNode {
  public ASTAssignation(int id) {
    super(id);
  }

  public ASTAssignation(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5425e99478f6c0e87c622214f9435ae8 (do not edit this line) */
