/* Generated By:JJTree: Do not edit this line. ASTContent.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTContent extends SimpleNode {
  public ASTContent(int id) {
    super(id);
  }

  public ASTContent(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5d77adedd7d07493093f58ab43c6ee34 (do not edit this line) */
