/* Generated By:JJTree: Do not edit this line. ASTFuncCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTFuncCall extends SimpleNode {
  public ASTFuncCall(int id) {
    super(id);
  }

  public ASTFuncCall(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6a0cb83228ca1a466f6f238d4d4fea1 (do not edit this line) */
