/* Generated By:JJTree: Do not edit this line. ASTFuncVarName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTFuncVarName extends SimpleNode {
  public ASTFuncVarName(int id) {
    super(id);
  }

  public ASTFuncVarName(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f26d11af6e951d9938d6016850f51ffa (do not edit this line) */
