/* Generated By:JJTree: Do not edit this line. ASTFuncName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTFuncName extends SimpleNode {
  public ASTFuncName(int id) {
    super(id);
  }

  public ASTFuncName(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb00efa717a4c82c6f7df6a28ed48719 (do not edit this line) */
