/* Generated By:JJTree: Do not edit this line. ASTFuncDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTFuncDecl extends SimpleNode {
  public ASTFuncDecl(int id) {
    super(id);
  }

  public ASTFuncDecl(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=caf99fe242c28e1eac214cd475eb733f (do not edit this line) */
