/* Generated By:JJTree: Do not edit this line. ASTIntBoolean.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTIntBoolean extends SimpleNode {
  public ASTIntBoolean(int id) {
    super(id);
  }

  public ASTIntBoolean(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2312ee0c1c2e9e93ded88aba772f2a6d (do not edit this line) */
