/* Generated By:JJTree: Do not edit this line. ASTIfBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTIfBlock extends SimpleNode {
  public ASTIfBlock(int id) {
    super(id);
  }

  public ASTIfBlock(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=27b4f54106fdb008dc03dcd89cee22e7 (do not edit this line) */
