/* Generated By:JJTree: Do not edit this line. ASTMathExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTMathExpr extends SimpleNode {
  public ASTMathExpr(int id) {
    super(id);
  }

  public ASTMathExpr(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c0a9b693e8f66b9b7db3f3a881d5870 (do not edit this line) */
