/* Generated By:JJTree: Do not edit this line. ASTprod.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTprod extends SimpleNode {
  public ASTprod(int id) {
    super(id);
  }

  public ASTprod(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2d495ede2166b5cd787b1508c94a8e5 (do not edit this line) */
