/* Generated By:JJTree: Do not edit this line. ASTProd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTProd extends SimpleNode {
  public ASTProd(int id) {
    super(id);
  }

  public ASTProd(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=068b9e21e0d4600e9c99c786c215753d (do not edit this line) */
