/* Generated By:JJTree: Do not edit this line. ASTReturns.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTReturns extends SimpleNode {
  public ASTReturns(int id) {
    super(id);
  }

  public ASTReturns(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e8eb399c4d3f94531e1342a2bb12f50f (do not edit this line) */
