/* Generated By:JJTree: Do not edit this line. ASTStringBoolean.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTStringBoolean extends SimpleNode {
  public ASTStringBoolean(int id) {
    super(id);
  }

  public ASTStringBoolean(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=68118434cfd85e9471fec30da1ac80bd (do not edit this line) */
