/* Generated By:JJTree: Do not edit this line. ASTStringLit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTStringLit extends SimpleNode {
  public ASTStringLit(int id) {
    super(id);
  }

  public ASTStringLit(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c64331c3622bd0a7113329d8f23c3fb (do not edit this line) */
