/* Generated By:JJTree: Do not edit this line. ASTTypedArgs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTTypedArgs extends SimpleNode {
  public ASTTypedArgs(int id) {
    super(id);
  }

  public ASTTypedArgs(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=24ca02c69fc7876a37e77049bb222f03 (do not edit this line) */
