/* Generated By:JJTree: Do not edit this line. ASTvaleur.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTvaleur extends SimpleNode {
  public ASTvaleur(int id) {
    super(id);
  }

  public ASTvaleur(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b953dc169421a2f8c5299a42a36c46cd (do not edit this line) */
