/* Generated By:JJTree: Do not edit this line. ASTVariableName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTVariableName extends SimpleNode {
  public ASTVariableName(int id) {
    super(id);
  }

  public ASTVariableName(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2515867b6a428b7384a5fc2a562ddf02 (do not edit this line) */
