/* Generated By:JJTree: Do not edit this line. ASTVarName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTVarName extends SimpleNode {
  public ASTVarName(int id) {
    super(id);
  }

  public ASTVarName(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=97af11a6e4732abcc26a7b13a0b27bb6 (do not edit this line) */
