/* Generated By:JJTree: Do not edit this line. ASTWhileBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package be.izanagi.simplelang;

public
class ASTWhileBlock extends SimpleNode {
  public ASTWhileBlock(int id) {
    super(id);
  }

  public ASTWhileBlock(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac6df3ecf319b3f07f8bf70c422e0ac5 (do not edit this line) */
