/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package be.izanagi.simplelang;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTIFBLOCK = 1;
  public int JJTWHILEBLOCK = 2;
  public int JJTFUNCDECL = 3;
  public int JJTRETURNS = 4;
  public int JJTDECLARATION = 5;
  public int JJTASSIGNATION = 6;
  public int JJTFUNCCALL = 7;
  public int JJTFUNCNAME = 8;
  public int JJTVARNAME = 9;
  public int JJTTYPEDARGS = 10;
  public int JJTARGS = 11;
  public int JJTTYPE = 12;
  public int JJTADD = 13;
  public int JJTTERM = 14;
  public int JJTFACTOR = 15;
  public int JJTINTBOOLEAN = 16;
  public int JJTSTRINGBOOLEAN = 17;
  public int JJTSTRINGLIT = 18;
  public int JJTNUMBER = 19;


  public String[] jjtNodeName = {
    "Start",
    "IfBlock",
    "WhileBlock",
    "FuncDecl",
    "Returns",
    "Declaration",
    "Assignation",
    "FuncCall",
    "FuncName",
    "VarName",
    "TypedArgs",
    "Args",
    "Type",
    "Add",
    "Term",
    "Factor",
    "IntBoolean",
    "StringBoolean",
    "StringLit",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=ee90056c32a34bc669e9e2013bd366ca (do not edit this line) */
