/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package be.izanagi.simplelang;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTASSIGNATION = 1;
  public int JJTCONTENT = 2;
  public int JJTVARIABLENAME = 3;
  public int JJTTYPE = 4;


  public String[] jjtNodeName = {
    "Start",
    "Assignation",
    "Content",
    "VariableName",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=e80231ea8647af5cbf116d42054283f9 (do not edit this line) */
