/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package be.izanagi.simplelang;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTASSIGNATION = 1;
  public int JJTFUNCCALL = 2;
  public int JJTFUNCVARNAME = 3;
  public int JJTARGS = 4;
  public int JJTTYPE = 5;
  public int JJTCONTENT = 6;
  public int JJTMATHEXPR = 7;
  public int JJTSOMME = 8;
  public int JJTPROD = 9;
  public int JJTVALEUR = 10;
  public int JJTNUMBER = 11;


  public String[] jjtNodeName = {
    "Start",
    "Assignation",
    "FuncCall",
    "FuncVarName",
    "Args",
    "Type",
    "Content",
    "MathExpr",
    "somme",
    "prod",
    "valeur",
    "number",
  };
}
/* JavaCC - OriginalChecksum=3ae046880732588fe0f98acab373d820 (do not edit this line) */
