/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package be.izanagi.simplelang;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENDLINE = 5;
  /** RegularExpression Id. */
  int TYPE = 6;
  /** RegularExpression Id. */
  int VNAME = 7;
  /** RegularExpression Id. */
  int ASSIGNSIGN = 8;
  /** RegularExpression Id. */
  int STRING = 9;
  /** RegularExpression Id. */
  int INT = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\",\"",
    "<TYPE>",
    "<VNAME>",
    "\"=\"",
    "<STRING>",
    "<INT>",
  };

}
